# Generated by Django 4.2.7 on 2023-11-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("County", models.CharField(max_length=40)),
                ("SubCounty", models.CharField(max_length=40)),
                ("Ward", models.CharField(max_length=40)),
                ("Building_name", models.CharField(max_length=40)),
                ("floor", models.IntegerField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.IntegerField(max_length=12)),
                ("email", models.EmailField(max_length=30)),
                ("date_of_birth", models.IntegerField(max_length=30)),
                ("nationality", models.CharField(max_length=30)),
                ("business_name", models.CharField(max_length=30)),
                (
                    "Business_category",
                    models.CharField(
                        choices=[
                            ("fintech", "Fintech"),
                            ("learning institution", "Learning Institution"),
                            ("transpotation", "Transportation"),
                        ],
                        default="fintech",
                        max_length=30,
                    ),
                ),
                ("business_registration_date", models.CharField(max_length=30)),
                ("businessAge", models.DurationField(default=None)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customerDetails.locationdetails",
                    ),
                ),
            ],
        ),
    ]
