# Generated by Django 4.2.7 on 2023-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerDetails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business", name="phone", field=models.CharField(max_length=12),
        ),
    ]
