# Generated by Django 4.2.7 on 2023-11-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerDetails", "0003_alter_business_businessage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="business_registration_date",
            field=models.DateField(max_length=30),
        ),
    ]
